/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package even.fibonacci.numbers;

/**
 *
 * @author can
 */
public class EvenFibonacciNumbers {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
     /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
        int y= 1;
        int z= 1;
        int toplam = 0;
        for (int i = 1; i <= 4000000; i++) {
            toplam +=z;
            System.out.println(z);
            y=z;
            z = y+z;
        }
        System.out.println(toplam);       
    }
    
}
